#!/usr/bin/env python3
"""Version bumping and changelog generation for Orisec HACS releases.

The GitHub release workflow drives this module, but every piece of logic is
importable and covered by ``tests/test_release.py`` so the release path can be
verified without running a workflow.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "custom_components" / "orisec" / "manifest.json"
CHANGELOG_PATH = REPO_ROOT / "CHANGELOG.md"

CHANGELOG_HEADER = "# Changelog\n"
CHANGELOG_INTRO = (
    "All notable changes to this project are documented here.\n"
    "Entries are generated by the release workflow from the commits in each release.\n"
)

RELEASE_TYPES = ("major", "minor", "patch")

VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:b(\d+))?$")
MANIFEST_VERSION_RE = re.compile(r'("version"\s*:\s*")([^"]*)(")')
RELEASE_COMMIT_RE = re.compile(r"^chore\(release\):\s*v?\d+\.\d+\.\d+(?:b\d+)?\s*$")
COMMIT_RE = re.compile(
    r"^(?P<type>[a-zA-Z]+)(?:\((?P<scope>[^)]*)\))?(?P<breaking>!)?:\s+(?P<description>.+)$"
)

# Conventional commit type -> changelog section. Anything unrecognised lands in
# "Other Changes" so a commit is never silently dropped from the changelog.
TYPE_SECTIONS = {
    "feat": "Features",
    "fix": "Bug Fixes",
    "perf": "Performance",
    "refactor": "Refactoring",
    "docs": "Documentation",
    "test": "Tests",
    "build": "Build System",
    "ci": "Continuous Integration",
    "chore": "Maintenance",
    "style": "Maintenance",
    "revert": "Reverts",
}

OTHER_SECTION = "Other Changes"
BREAKING_SECTION = "Breaking Changes"

SECTION_ORDER = (
    BREAKING_SECTION,
    "Features",
    "Bug Fixes",
    "Performance",
    "Refactoring",
    "Documentation",
    "Tests",
    "Build System",
    "Continuous Integration",
    "Reverts",
    "Maintenance",
    OTHER_SECTION,
)


class ReleaseError(RuntimeError):
    """Raised when a release cannot be prepared."""


class Commit:
    """A single commit considered for the changelog."""

    def __init__(self, sha: str, subject: str, body: str = "") -> None:
        self.sha = sha
        self.subject = subject
        self.body = body

    @property
    def short_sha(self) -> str:
        return self.sha[:7]

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"Commit({self.short_sha!r}, {self.subject!r})"


def parse_version(version: str) -> tuple[int, int, int, int | None]:
    """Parse ``major.minor.patch`` or ``major.minor.patchbN`` into its parts.

    The fourth element is the PEP 440 beta number, or ``None`` for a stable
    version. ``0.2.0b1`` parses as ``(0, 2, 0, 1)``.
    """
    match = VERSION_RE.match(version.strip())
    if match is None:
        raise ReleaseError(f"Version {version!r} is not a major.minor.patch[bN] version")
    beta = match.group(4)
    return (
        int(match.group(1)),
        int(match.group(2)),
        int(match.group(3)),
        int(beta) if beta is not None else None,
    )


def bump_version(version: str, release_type: str, *, beta: bool = False) -> str:
    """Return ``version`` bumped by ``release_type``.

    Once a beta line is open the base version is already decided, so
    ``release_type`` no longer applies to it: a further beta increments the beta
    number and a stable run promotes the same base. Both ignore ``release_type``.

        0.1.0    minor, beta -> 0.2.0b1
        0.2.0b1  minor, beta -> 0.2.0b2   (same base, next beta)
        0.2.0b2  minor       -> 0.2.0     (promoted unchanged)
    """
    if release_type not in RELEASE_TYPES:
        raise ReleaseError(f"Release type {release_type!r} must be one of {', '.join(RELEASE_TYPES)}")

    major, minor, patch, current_beta = parse_version(version)

    if current_beta is not None:
        base = f"{major}.{minor}.{patch}"
        return f"{base}b{current_beta + 1}" if beta else base

    if release_type == "major":
        base = f"{major + 1}.0.0"
    elif release_type == "minor":
        base = f"{major}.{minor + 1}.0"
    else:
        base = f"{major}.{minor}.{patch + 1}"

    return f"{base}b1" if beta else base


def is_beta(version: str) -> bool:
    """Return whether ``version`` is a beta."""
    return parse_version(version)[3] is not None


def read_manifest_version(manifest_path: Path = MANIFEST_PATH) -> str:
    """Read the integration version, the source of truth HACS also reads."""
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except FileNotFoundError as err:
        raise ReleaseError(f"Manifest not found at {manifest_path}") from err
    except json.JSONDecodeError as err:
        raise ReleaseError(f"Manifest at {manifest_path} is not valid JSON: {err}") from err

    version = manifest.get("version")
    if not isinstance(version, str) or not version:
        raise ReleaseError(f"Manifest at {manifest_path} has no usable 'version' field")
    return version


def write_manifest_version(version: str, manifest_path: Path = MANIFEST_PATH) -> None:
    """Write ``version`` back to the manifest.

    The version field is replaced in place rather than re-serialised, so the
    release commit only ever shows the version change and never a reformat of
    the surrounding manifest.
    """
    parse_version(version)
    contents = manifest_path.read_text(encoding="utf-8")
    updated, replacements = MANIFEST_VERSION_RE.subn(rf"\g<1>{version}\g<3>", contents, count=1)
    if replacements != 1:
        raise ReleaseError(f"Manifest at {manifest_path} has no 'version' field to update")
    manifest_path.write_text(updated, encoding="utf-8")


def _git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def latest_tag(*, stable_only: bool = False) -> str | None:
    """Return the most recent reachable tag, or ``None`` for a first release.

    With ``stable_only`` the beta tags are skipped, so a stable release reports
    every change since the last stable one rather than only since its last beta.
    """
    args = ["describe", "--tags", "--abbrev=0"]
    if stable_only:
        args.append("--exclude=*b[0-9]*")
    try:
        return _git(*args) or None
    except subprocess.CalledProcessError:
        return None


def collect_commits(since_tag: str | None = None) -> list[Commit]:
    """Collect non-merge commits made since ``since_tag`` (or the whole history)."""
    revision_range = f"{since_tag}..HEAD" if since_tag else "HEAD"
    raw = _git(
        "log",
        revision_range,
        "--no-merges",
        "--format=%H%x1f%s%x1f%b%x1e",
    )
    return parse_git_log(raw)


def parse_git_log(raw: str) -> list[Commit]:
    """Parse the unit/record separated ``git log`` output into commits."""
    commits: list[Commit] = []
    for record in raw.split("\x1e"):
        record = record.strip("\n")
        if not record.strip():
            continue
        sha, _, remainder = record.partition("\x1f")
        subject, _, body = remainder.partition("\x1f")
        commits.append(Commit(sha.strip(), subject.strip(), body.strip()))
    return commits


def _is_breaking(commit: Commit, match: re.Match[str] | None) -> bool:
    if match is not None and match.group("breaking"):
        return True
    return any(line.startswith(("BREAKING CHANGE:", "BREAKING-CHANGE:")) for line in commit.body.splitlines())


def classify_commit(commit: Commit) -> tuple[str, str]:
    """Return the ``(section, entry)`` a commit contributes to the changelog."""
    match = COMMIT_RE.match(commit.subject)
    breaking = _is_breaking(commit, match)

    known_section = TYPE_SECTIONS.get(match.group("type").lower()) if match is not None else None

    if known_section is None:
        # An unrecognised or absent type prefix still carries meaning, so keep
        # the subject verbatim rather than stripping it.
        description = commit.subject
    else:
        description = match.group("description").strip()
        scope = match.group("scope")
        if scope:
            description = f"**{scope.strip()}**: {description}"

    if breaking:
        section = BREAKING_SECTION
    else:
        section = known_section or OTHER_SECTION

    return section, f"{description} ({commit.short_sha})"


def is_release_commit(commit: Commit) -> bool:
    """Return whether a commit is the workflow's own version bump commit."""
    return RELEASE_COMMIT_RE.match(commit.subject) is not None


def build_sections(commits: list[Commit]) -> dict[str, list[str]]:
    """Group commits into ordered changelog sections."""
    sections: dict[str, list[str]] = {}
    for commit in commits:
        if is_release_commit(commit):
            continue
        section, entry = classify_commit(commit)
        sections.setdefault(section, []).append(entry)

    return {name: sections[name] for name in SECTION_ORDER if name in sections}


def render_release_notes(
    version: str,
    sections: dict[str, list[str]],
    *,
    repository: str | None = None,
    previous_tag: str | None = None,
    release_date: str | None = None,
) -> str:
    """Render the markdown notes used for both the release and the changelog."""
    release_date = release_date or date.today().isoformat()
    lines = [f"## v{version} - {release_date}", ""]

    if sections:
        for name, entries in sections.items():
            lines.append(f"### {name}")
            lines.extend(f"- {entry}" for entry in entries)
            lines.append("")
    else:
        lines.extend(["No user facing changes were recorded for this release.", ""])

    if repository:
        base = f"https://github.com/{repository}"
        if previous_tag:
            link = f"{base}/compare/{previous_tag}...v{version}"
        else:
            link = f"{base}/commits/v{version}"
        lines.extend([f"**Full Changelog**: {link}", ""])

    return "\n".join(lines).rstrip("\n") + "\n"


def prepend_changelog(existing: str, entry: str) -> str:
    """Insert ``entry`` above the existing releases, keeping the file header."""
    header = f"{CHANGELOG_HEADER}\n{CHANGELOG_INTRO}"
    body = existing

    if existing.startswith(CHANGELOG_HEADER):
        body = existing[len(CHANGELOG_HEADER) :]
        intro_marker = f"\n{CHANGELOG_INTRO}"
        if body.startswith(intro_marker):
            body = body[len(intro_marker) :]

    body = body.lstrip("\n")
    return f"{header}\n{entry.rstrip()}\n" + (f"\n{body}" if body else "")


def update_changelog(entry: str, changelog_path: Path = CHANGELOG_PATH) -> None:
    """Write ``entry`` to the top of the changelog, creating it when missing."""
    existing = changelog_path.read_text(encoding="utf-8") if changelog_path.exists() else ""
    changelog_path.write_text(prepend_changelog(existing, entry), encoding="utf-8")


def write_outputs(outputs: dict[str, str]) -> None:
    """Expose values to later workflow steps via ``$GITHUB_OUTPUT``."""
    output_file = os.environ.get("GITHUB_OUTPUT")
    if not output_file:
        return

    with open(output_file, "a", encoding="utf-8") as handle:
        for key, value in outputs.items():
            if "\n" in value:
                handle.write(f"{key}<<__RELEASE_EOF__\n{value}\n__RELEASE_EOF__\n")
            else:
                handle.write(f"{key}={value}\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--release-type", required=True, choices=RELEASE_TYPES)
    parser.add_argument(
        "--repository",
        default=os.environ.get("GITHUB_REPOSITORY"),
        help="owner/name used to build the compare link",
    )
    parser.add_argument(
        "--notes-file",
        type=Path,
        help="write the rendered release notes to this file",
    )
    parser.add_argument(
        "--beta",
        action="store_true",
        help="publish a beta of the bumped version (0.2.0b1) instead of a stable release",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="render the notes without editing the manifest or changelog",
    )
    args = parser.parse_args(argv)

    try:
        previous_version = read_manifest_version()
        new_version = bump_version(previous_version, args.release_type, beta=args.beta)
        prerelease = is_beta(new_version)
        # A stable release reports everything since the last stable tag, so the
        # changes already shipped in its betas are not lost from the changelog.
        previous_tag = latest_tag(stable_only=not prerelease)
        notes = render_release_notes(
            new_version,
            build_sections(collect_commits(previous_tag)),
            repository=args.repository,
            previous_tag=previous_tag,
        )

        if not args.dry_run:
            write_manifest_version(new_version)
            # Betas are transient, so they stay out of the changelog; the stable
            # release that promotes them carries their entries instead.
            if not prerelease:
                update_changelog(notes)
        if args.notes_file:
            args.notes_file.write_text(notes, encoding="utf-8")
    except ReleaseError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1

    write_outputs(
        {
            "previous_version": previous_version,
            "previous_tag": previous_tag or "",
            "version": new_version,
            "tag": f"v{new_version}",
            "prerelease": "true" if prerelease else "false",
            "notes": notes,
        }
    )
    print(notes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
